sudo: required
dist: trusty


language: ruby


services:
  - docker


before_install:
  - docker pull bhntools/debcirclnode:latest


script:
  - docker run  -it  --host 192.168.99.100  bhntools/debcirclnode:latest
