version: 2
jobs:
 build:
  docker:
   - image: bhntools/debcirclnode:latest
  steps:
   - checkout
   - run: echo "First hello circleci."
   - run: node -v

test:
  override:
    - "docker bhntools/debcirclnode:latest node -v"
