machine:
        node:
                version: 9.3.0
        services:
                - docker

dependencies:
        override:
                - docker build -t bhntools/debcirclnode:latest .

test:
        override:
                - docker run bhntools/debcirclnode ng serve --host 0.0.0.0 --port 4200

deployment:
        production:
                branch: master
                commands:
                        - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
                        - ./deploy.sh
