machine:
  node:
    version: 0.11.8
    
 service:
    - docker

dependencies:
 override:
  - docker info
  - docker build --rm=false -t bhntools/debcirclnode:latest
  - yarn add ava tap-xunit --dev # or you could use npm

test:
 override:
    - docker run -d --name nodangl -p 4200:4200  bhntools/debcirclnode:latest sleep 10
    - curl --retry 10 --retry-delay 5 -v http://localhost:4200
    - mkdir -p $CIRCLE_TEST_REPORTS/reports
    - ava --tap | tap-xunit > $CIRCLE_TEST_REPORTS/reports/ava.xml
    
deployment:
 hub:
  branch: master
  commands:
    - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
    - ./deploy.sh
