version: 2
jobs:
  build:
    docker:
      - image: bhntools/debcirclnode:latest
    steps:
      - checkout
      - run: echo "First hello debcirclnode."
      - run: node -v
test:
  override:
    - docker run -p 4200:4200  -it bhntools/debcirclnode:latest node -v